### ISSUE TITLE
Count "pale"

### ISSUE THREAD

**Issue by jgfoster** [AllenDowney/ThinkPython#27]
"By my count, these words appear 223 times in a book that contains about 461,000 words."

I get 228 out of 469,262. I'm just curious to know if I miscounted!

```
import re

pale_count = 0
words = set()
word_count = 0
for line in open('pg1184_cleaned.txt'):
  search = re.findall(r'[a-z]+', line.lower().strip())
  word_count += len(search)
  for word in search:
    if word in ['pale', 'pales', 'paled', 'paleness', 'pallor']:
      words.add(word)
      pale_count += 1
print(pale_count, word_count, words)

228 469262 {'paleness', 'paled', 'pallor', 'pale'}
```

**Comment by AllenDowney** [comment]
Your solution is correct, but more complex that I expect a reader to write at this point in the book. The intent is to use regex to find all lines that contain the words -- and some lines contain more than one of these words. I have revised the question to clarify that it should count lines rather than words.
